# Generated by Django 3.2.8 on 2021-10-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_title', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('day', models.CharField(blank=True, max_length=55, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('float_price', models.IntegerField(blank=True, null=True)),
                ('button_text', models.CharField(blank=True, max_length=55, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
