# Generated by Django 3.2.8 on 2021-10-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Sliders'},
        ),
    ]
